const state = {
  // 对应国家参考文档 https://blog.csdn.net/shenenhua/article/details/79150053
  countriesList: [
    { code: "zhCN", country: "中国" },
    { code: "zhHK",  country: "香港" },
    { code: "zhTW", country: "台湾" },
    { code: "ar", country: "阿拉伯" },
    { code: "bgBG", country: "保加利亚" },
    { code: "bs", country: "波斯尼亚" },
    { code: "ca", country: "嘉泰罗尼亚" },
    { code: "csCZ", country: "捷克" },
    { code: "daDK", country: "丹麦" },
    { code: "de", country: "德国" },
    { code: "elGR", country: "希腊" },
    { code: "enUS", country: "美国" },
    { code: "es", country: "西班牙" },
    { code: "esES", country: "西班牙" },
    { code: "etEE", country: "爱沙尼亚" },
    { code: "faIR", country: "伊朗" },
    { code: "fiFI", country: "芬兰" },
    { code: "fr", country: "法国" },
    { code: "hiIN", country: "印度" },
    { code: "hrHR", country: "克罗埃西亚" },
    { code: "huHU", country: "匈牙利" },
    { code: "inID", country: "印尼" },
    { code: "it", country: "意大利" },
    { code: "iw", country: "希伯来" },
    { code: "jaJP", country: "日本" },
    { code: "ko", country: "韩国" },
    { code: "ltLT", country: "立陶宛" },
    { code: "lvLV", country: "拉脱维亚" },
    { code: "mk", country: "马其顿" },
    { code: "msMY", country: "马来西亚" },
    { code: "myMM", country: "缅甸" },
    { code: "nbNO", country: "挪威" },
    { code: "nl", country: "荷兰" },
    { code: "plPL", country: "波兰" },
    { code: "ptBR", country: "巴西" },
    { code: "ptPT", country: "葡萄牙" },
    { code: "roRO", country: "罗马尼亚" },
    { code: "ruRU", country: "俄国" },
    { code: "skSK", country: "斯洛伐克" },
    { code: "slSI", country: "斯洛文尼亚" },
    { code: "sr", country: "塞尔维亚" },
    { code: "svSE", country: "瑞典" },
    { code: "thTH", country: "泰国" },
    { code: "trTR", country: "土耳其" },
    { code: "ukUA", country: "乌克兰" },
    { code: "viVN", country: "越南" },
  ],
};

const mutations = {};

export { state, mutations };
